<div id="livechat" class="closed">
	<div class="title">
		<?php echo __('Contact Us'); ?>
	</div>
	<div class="discussion">
		<div id="livedisc"></div>
	</div>
	<form id="livechatform" action="<?php echo $this->getFormAction(); ?>" type="post">
		<textarea id="message" name="message" placeholder="<?php echo __('Type and press [enter]'); ?>"></textarea> 
	</form>
</div>
<script type="text/javascript">
	require(['jquery'], function($){ 
     	$('#livechat .title').click(function(){
     		if($('#livechat').hasClass('closed')){
     			$('#livechat').removeClass('closed');
     		}else{
     			$('#livechat').addClass('closed');
     		}
     	})
     	$('#message').keypress(function (e) {
		  	if (e.which == 13) {
		    	$('#livechatform').submit();
		    	return false;
		  	}
		});
     	$("#livechatform").submit(function(e) {
		    var url = "<?php echo $this->getFormAction(); ?>";
		    $.ajax({
	           	type: "POST",
	           	url: url,
	           	data: $("#livechatform").serialize(),
	           	success: function(data){
	           		var message = $('#message').val();
	           		$('#livedisc').append('<div class="message customer">'+message+'</div>');
	           		$('#message').val('');
	           		console.log('Success!');
	               	console.log(data);
	           	},
	            error: function (data) {
	                console.log('An error occurred.');
	                console.log(data);
	            }
		    });
		    e.preventDefault();
		});
 	});
</script>