<div id="livechat" class="closed">
	<div class="title">
		<?php echo __('Contact Us'); ?>
	</div>
	<div class="discussion">
		<div id="livedisc"></div>
		<form id="livechatform" action="<?php echo $this->getFormAction(); ?>" type="post">
			<textarea id="message" name="message" placeholder="<?php echo __('What do you need?'); ?>"></textarea> 
			<button type="submit" title="Submit" class="action submit primary">
	            <span><?php echo __('Submit'); ?></span>
	        </button>
		</form>
	</div>
</div>
<script type="text/javascript">
	require(['jquery'], function($){ 
     	$('#livechat .title').click(function(){
     		if($('#livechat').hasClass('closed')){
     			$('#livechat').removeClass('closed');
     		}else{
     			$('#livechat').addClass('closed');
     		}
     	})
     	$("#livechatform").submit(function(e) {
		    var url = "<?php echo $this->getFormAction(); ?>";
		    $.ajax({
	           	type: "POST",
	           	url: url,
	           	data: $("#livechatform").serialize(),
	           	success: function(data){
	           		var message = $('#message').val();
	           		$('#livedisc').append('<div class="message customer">'+message+'</div>');
	           		$('#message').val('');
	           		console.log('Success!');
	               	console.log(data);
	           	},
	            error: function (data) {
	                console.log('An error occurred.');
	                console.log(data);
	            }
		    });
		    e.preventDefault();
		});
 	});
</script>