<div id="lc-livechat">
	<div class="loading-mask" data-role="loader" style="display: none;">
		<div class="popup popup-loading">
			<div class="popup-inner">
				<img alt="Loading..." src="http://127.0.0.1/pub/static/adminhtml/Magento/backend/en_US/images/loader-2.gif">
				Please wait...
			</div>
		</div>
	</div>
	<div class="title">
		<?php echo __('Contact Us'); ?>
	</div>
	<div id="lc-discussion">
		<div id="lc-livedisc"></div>
	</div>
	<form id="lc-livechatform" action="<?php echo $this->getFormAdminAction(); ?>" type="post">
		<textarea id="lc-message" name="message" placeholder="<?php echo __('Type and press [enter]'); ?>"></textarea> 
		<input type="hidden" name="session" id="livechat-session-id" />
	</form>
</div>
<script type="text/javascript">
	require(['jquery', 'domReady!'], function($){ 
		/* Tab click event*/
		$('#livechat_tabs_ul li').click(function(){
			$('#livechat_tabs_ul li').removeClass('ui-tabs-active ui-state-active');
			$(this).addClass('ui-tabs-active ui-state-active');
			var sessionId = $(this).attr('data-session-id');
			$('#livechat-session-id').val(sessionId);
			$('#lc-livedisc').empty();
			$('#lc-livechat .loading-mask').show();
			loadMessages();
		})
		/**/
		/* ********************* Loading Discussion ******************* */
		
		if($('ul#livechat_tabs_ul li').length >= 1){
			$('#lc-livechat .loading-mask').show();
			var sessionId = $('ul#livechat_tabs_ul li').first().attr('data-session-id');
			$('#livechat-session-id').val(sessionId);
			loadMessages();
		}
		/**/
		
		
     	$('#lc-message').keypress(function (e) {
		  	if (e.which == 13) {
		    	$('#lc-livechatform').submit();
		    	return false;
		  	}
		});
     	$("#lc-livechatform").submit(function(e) {
		    var url = "<?php echo $this->getFormAdminAction(); ?>";
		    $.ajax({
	           	type: "POST",
	           	url: url,
	           	data: $("#lc-livechatform").serialize(),
	           	success: function(data){
	           		var message = $('#lc-message').val();
	           		$('#lc-livedisc').append('<div class="lc-message admin">'+message+'</div>');
	           		$('#lc-message').val('');
	           		$('#lc-livedisc').animate({bottom: 0});
	           		changeProportions();
	           		console.log('Success!');
	           	},
	            error: function (data) {
	                console.log('An error occurred.');
	            }
		    });
		    e.preventDefault();
		});
		function loadMessages(){
			var url = "/livechat/message/load";
			var className = "";
			var messageS = "";
			var html = ""
			console.log($('#livechat-session-id').val());
		   $.ajax({
	           	type: "POST",
	           	url: url,
	           	data: {'session-id': $('#livechat-session-id').val()},
	           	success: function(data){
	           		for (var i = 0; i < data.length; i++) {
	           			console.log(data[i].message);
	           			
   						 if(data[i].is_admin == 1){
   						 		className = "admin";
   						 }else {
   						 		className = "customer";
   						 }
   						 messageS = data[i].message;
   						 html = '<div class="lc-message '+ className +'">'+ messageS +'</div>';
   						 $('#lc-livedisc').append(html);
   						 console.log(className);
   						 changeProportions();
   						 
						}
	           		console.log('Success!');
	           		console.log(data);
	               $('#lc-livechat .loading-mask').hide();
	           	},
	            error: function (data) {
	                console.log('An error occurred.');
	            }
		   });
		}
		function changeProportions(){
			var L = $('#lc-livedisc').height();
			var l = 350;
			var H = 350;
			var h = 0;
			var p = L / l; //   p = Proportion
			if (p <= 1){
			}else{
				if($('#lc-discussion').find('#lc-scrollBar').length !== 0){
					setAppropriateScrollbarHeight();
				}else{
					$('#lc-discussion').prepend('<div id="lc-scrollBar"><div id="lc-slider"></div></div>');
					setAppropriateScrollbarHeight();
					var isDragging = false;
					var scrollClicked = false;

					$("#lc-scrollBar").mousedown(function(e) {
						scrollClicked = true;
						$('#lc-slider').addClass('grabbing');
					});
					$("#lc-scrollBar").mousemove(function(e){
						isDragging = true;
						if(isDragging && scrollClicked){
					        var cursorY = e.clientY || window.event.clientY;
						    var scrollBarYPosition = $('#lc-scrollBar')[0].getBoundingClientRect().top;
						    var difference = cursorY - scrollBarYPosition;
						    var lcSliderHeight = document.getElementById('lc-slider').clientHeight;

						    var L = $('#lc-livedisc').height();
							var l = 350;
							var diffL = L -l;

						    if((lcSliderHeight/2) >= difference){  // top
						    	$('#lc-slider').css('top', 0 + 'px');
						    	$('#lc-livedisc').css('bottom', '-' + diffL + 'px');
						    	console.log( '-' + diffL + 'px');
						    }else if((350 - (lcSliderHeight/2)) <= difference){  //bottom
						    	$('#lc-slider').css('top', (350 - lcSliderHeight) + 'px');
						    	$('#lc-livedisc').css('bottom', 0 + 'px');
						    	console.log( 0 + 'px');
						    }else{ // middle
						    	$('#lc-slider').css('top', (difference - (lcSliderHeight/2))  + 'px');
						    	$('#lc-livedisc').css('bottom', '-' + (L-(l/2)-(L*(difference/l))) + 'px');
						    	console.log( '-' + (L-(l/2)-(L*(difference/l))) + 'px');
						    }
						}
				    });
				    $("#lc-scrollBar").mouseup(function() {
					    isDragging = false;
					    scrollClicked = false;
					    $('#lc-slider').removeClass('grabbing');
					});
				}
			}
		}
		function setAppropriateScrollbarHeight(){
			var L = $('#lc-livedisc').height();
			var l = 350;
			var H = 350;
			var h = 0;
			h = (H*l)/L;
			if(h < 10){
				$('#lc-slider').height(10);
				$('#lc-slider').css('top', (H-10) + 'px');
			}else{
				$('#lc-slider').height(h);
				$('#lc-slider').css('top', (H-h) + 'px');
			}
		}
 	});
</script>