<div id="lc-livechat" class="closed">
	<div class="title">
		<?php echo __('Contact Us'); ?>
	</div>
	<div id="lc-discussion">
		<div id="lc-livedisc"></div>
	</div>
	<form id="lc-livechatform" action="<?php echo $this->getFormAdminAction(); ?>" type="post">
		<textarea id="lc-message" name="message" placeholder="<?php echo __('Type and press [enter]'); ?>"></textarea> 
	</form>
</div>
<script type="text/javascript">
	require(['jquery'], function($){ 
     	$('#lc-livechat .title').click(function(){
     		if($('#lc-livechat').hasClass('closed')){
     			$('#lc-livechat').removeClass('closed');
     		}else{
     			$('#lc-livechat').addClass('closed');
     		}
     	})
     	$('#lc-message').keypress(function (e) {
		  	if (e.which == 13) {
		    	$('#lc-livechatform').submit();
		    	return false;
		  	}
		});
     	$("#lc-livechatform").submit(function(e) {
		    var url = "<?php echo $this->getFormAction(); ?>";
		    $.ajax({
	           	type: "POST",
	           	url: url,
	           	data: $("#lc-livechatform").serialize(),
	           	success: function(data){
	           		var message = $('#lc-message').val();
	           		$('#lc-livedisc').append('<div class="message customer">'+message+'</div>');
	           		$('#lc-message').val('');
	           		$('#lc-livedisc').animate({bottom: 0});
	           		changeProportions();
	           		console.log('Success!');
	               	console.log(data);
	           	},
	            error: function (data) {
	                console.log('An error occurred.');
	                console.log(data);
	            }
		    });
		    e.preventDefault();
		});
		function changeProportions(){
			var L = $('#lc-livedisc').height();
			var l = 230;
			var H = 230;
			var h = 0;
			var p = L / l; //   p = Proportion
			if (p <= 1){
			}else{
				if($('#lc-discussion').find('#lc-scrollBar').length !== 0){
					setAppropriateScrollbarHeight();
				}else{
					$('#lc-discussion').prepend('<div id="lc-scrollBar"><div id="lc-slider"></div></div>');
					setAppropriateScrollbarHeight();
					var isDragging = false;
					var scrollClicked = false;

					$("#lc-scrollBar").mousedown(function(e) {
						scrollClicked = true;
						$('#lc-slider').addClass('grabbing');
					});
					$("#lc-scrollBar").mousemove(function(e){
						isDragging = true;
						if(isDragging && scrollClicked){
					        var cursorY = e.clientY || window.event.clientY;
						    var scrollBarYPosition = $('#lc-scrollBar')[0].getBoundingClientRect().top;
						    var difference = cursorY - scrollBarYPosition;
						    var lcSliderHeight = document.getElementById('lc-slider').clientHeight;

						    var L = $('#lc-livedisc').height();
							var l = 230;
							var diffL = L -l;

						    if((lcSliderHeight/2) >= difference){  // top
						    	$('#lc-slider').css('top', 0 + 'px');
						    	$('#lc-livedisc').css('bottom', '-' + diffL + 'px');
						    	console.log( '-' + diffL + 'px');
						    }else if((230 - (lcSliderHeight/2)) <= difference){  //bottom
						    	$('#lc-slider').css('top', (230 - lcSliderHeight) + 'px');
						    	$('#lc-livedisc').css('bottom', 0 + 'px');
						    	console.log( 0 + 'px');
						    }else{ // middle
						    	$('#lc-slider').css('top', (difference - (lcSliderHeight/2))  + 'px');
						    	$('#lc-livedisc').css('bottom', '-' + (L-(l/2)-(L*(difference/l))) + 'px');
						    	console.log( '-' + (L-(l/2)-(L*(difference/l))) + 'px');
						    }
						}
				    });
				    $("#lc-scrollBar").mouseup(function() {
					    isDragging = false;
					    scrollClicked = false;
					    $('#lc-slider').removeClass('grabbing');
					});
				}
			}
		}
		function setAppropriateScrollbarHeight(){
			var L = $('#lc-livedisc').height();
			var l = 230;
			var H = 230;
			var h = 0;
			h = (H*l)/L;
			if(h < 10){
				$('#lc-slider').height(10);
				$('#lc-slider').css('top', (H-10) + 'px');
			}else{
				$('#lc-slider').height(h);
				$('#lc-slider').css('top', (H-h) + 'px');
			}
		}
 	});
</script>